#!/bin/sh

# Time Arithmetic

MAXDUR=360
TIME1=`cat /var/log/weather-app-sent`
TIME2=`date +%H:%M:%S`

# Convert the times to seconds from the Epoch
SEC1=`date +%s -d ${TIME1}`
SEC2=`date +%s -d ${TIME2}`

# Use expr to do the math, let's say TIME1 was the start and TIME2 was the finish
DIFFSEC=`expr ${SEC2} - ${SEC1}`

if [ "$DIFFSEC" -ge "$MAXDUR" ];
then
   echo "1"
else
   echo "0"
fi

exit