#!/bin/sh

APP=/usr/local/rain/RainDetectorGallant
OPTIONS="--sampleRate 8000 --sampleFormat INT16"

[ -e ${APP} ] || exit 1

while [ 1 ] ; do 
	${APP} ${OPTIONS} >> /var/log/rainfall.log 2>&1
	sleep 10
done
