#!/bin/sh

if [ ! -e /usr/share/.mono/certs ] ; then
        mount / -o remount,rw
        mono /usr/lib/mono/4.5/mozroots.exe --import --machine --ask-remove --file /etc/ssl/certdata.txt
        mount / -o remount,ro
fi
