#!/bin/sh
### BEGIN INIT INFO
# Provides:          gallant
# Required-Start:    
# Required-Stop:     $local_fs
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: 
# Description:       
#                    
### END INIT INFO
#

[ -f /etc/default/rcS ] && . /etc/default/rcS

case "$1" in
        start) 
		mount / -o remount,rw 
		echo "Starting gallant - `date`" >> /var/debug-log
		mount / -o remount,ro
		modprobe lora_raw_driver
		modprobe lora_raw_chardev
		#mono /usr/lib/mono/4.5/mozroots.exe --import --machine --sync --file /etc/init.d/certdata.txt
		/usr/local/bin/access-gps
		/etc/init.d/gallant.sh &
		/etc/init.d/intellifarm.sh &
		/etc/init.d/raincheck &
		exit 0;
                ;;
	stop)
		exit 0
                ;;
        *)
                echo "Usage: gallant {start|stop}" >&2
                exit 1
                ;;
esac
