#!/bin/sh

start() 
{
	/usr/local/bin/led-manager
	# Call script to check for modem completion in background
	/etc/init.d/checkmodem &
}

stop()
{
	/usr/local/bin/led-manager device shutdown
}

restart()
{
	stop
	sleep 3
	start
}

case "$1" in
  start)
       start
       ;;
  stop)
       stop
       ;;
  restart|reload)
       restart
       ;;
  *)
       echo $"Usage: $0 {start|stop|restart}"
       exit 1
esac

