#!/bin/sh

# Variables
I2CBUS=0

# Color selections
red='\033[1;31m'
green='\033[1;32m'
blue='\033[1;34m'
resetColor='\033[0m'

# Results
PASS=${green}PASS
FAIL=${red}FAIL


printf "${blue}TESTING STC3115\n"
printf "${resetColor}Test for driver presence		"
if [ -e /sys/bus/i2c/drivers/stc3115 ]
then
	printf "$PASS\n"
	printf "${resetColor}Test for device presence		"
	if [ -d /sys/bus/i2c/devices/$I2CBUS-0070 ]
	then
		printf "$PASS\n"
		
		printf "${resetColor}Test driver name in device		"
		temp=`cat /sys/bus/i2c/devices/${I2CBUS}-0070/name`
		if [ "$temp" = "stc3115" ]
		then
			printf "$PASS\n"
		else
			printf "$FAIL\n"
		fi
		
		printf "${resetColor}Test voltage		"
		temp=`cat /sys/class/power_supply/battery/voltage_now`
		if [[ $temp =~ ^-?[0-9]+$ ]]
		then
			printf "$PASS\n"
		else
			printf "$FAIL\n"
		fi

		printf "${resetColor}Test capacity		"
		temp=`cat /sys/class/power_supply/battery/capacity`
		if [[ $temp =~ ^-?[0-9]+$ ]]
		then
			printf "$PASS\n"
		else
			printf "$FAIL\n"
		fi

		printf "${resetColor}Test current		"
		temp=`cat /sys/class/power_supply/battery/current_now`
		if [[ $temp =~ ^-?[0-9]+$ ]]
		then
			printf "$PASS\n"
		else
			printf "$FAIL\n"
		fi

		printf "${resetColor}Test temperature		"
		temp=`cat /sys/class/power_supply/battery/temp`
		if [[ $temp =~ ^-?[0-9]+$ ]]
		then
			printf "$PASS\n"
		else
			printf "$FAIL\n"
		fi
	else
		printf "$FAIL\n"
		printf "${resetColor}Due to the absence of the device, all other tests for this driver will be skipped\n"
	fi
else
	printf "$FAIL\n"
	printf "${resetColor}Due to the absence of the driver, all other tests for this driver will be skipped\n"
fi


printf "${resetColor}\n"
