#!/bin/sh

# Variables
I2CBUS=0

# Color selections
red='\033[1;31m'
green='\033[1;32m'
blue='\033[1;34m'
resetColor='\033[0m'

# Results
PASS=${green}PASS
FAIL=${red}FAIL


printf "${blue}TESTING LTR303\n"
printf "${resetColor}Test for driver presence		"
if [ -e /sys/bus/i2c/drivers/ltr303 ]
then
	printf "$PASS\n"
	printf "${resetColor}Test for device presence		"
	if [ -d /sys/bus/i2c/devices/$I2CBUS-0029 ]
	then
		printf "$PASS\n"
		
		printf "${resetColor}Test driver name in device		"
		temp=`cat /sys/bus/i2c/devices/${I2CBUS}-0029/name`
		if [ "$temp" = "ltr303" ]
		then
			printf "$PASS\n"
		else
			printf "$FAIL\n"
		fi
		
		printf "${resetColor}Test illuminance		"
		echo 1 > /sys/bus/i2c/devices/$I2CBUS-0029/enable_als_sensor
		temp=`find /sys/bus/i2c/devices/${I2CBUS}-0029/ -name 'lux_adc' -exec cat {} \;`
                echo $temp > tmp                                            
                sort -u tmp                                                 
                temp2=`cat tmp`                                                
                temp="$(echo -e "${temp2}" | tr -d '[[:space:]]')" 
		if [[ $temp =~ ^-?[0-9]+$ ]]
		then
			printf "$PASS\n"
		else
			printf "$FAIL\n"
		fi

	else
		printf "$FAIL\n"
		printf "${resetColor}Due to the absence of the device, all other tests for this driver will be skipped\n"
	fi
else
	printf "$FAIL\n"
	printf "${resetColor}Due to the absence of the driver, all other tests for this driver will be skipped\n"
fi


printf "${resetColor}\n"
